//
//  WTClient.h
//  WeTongji
//
//  Created by 紫川 王 on 12-4-23.
//  Copyright (c) 2012年 Tongji Apple Club. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "ASIFormDataRequest.h"

@class WTClient;

typedef void (^WTCompletionBlock)(WTClient *client);

@interface WTClient : NSObject <ASIHTTPRequestDelegate> {
    WTCompletionBlock _completionBlock;
}

@property (nonatomic, assign) BOOL hasError;
@property (nonatomic, copy) NSString* errorDesc;
// Status code generated by server side application
@property (nonatomic, assign) int responseStatusCode;
// NSDictionary or NSArray
@property (nonatomic, retain) NSDictionary *responseData;

- (void)setCompletionBlock:(void (^)(WTClient* client))completionBlock;
- (WTCompletionBlock)completionBlock;
// return an autoreleased object, while gets released after one of following calls complete
+ (id)client;

- (void)getActivitesWithChannelIds:(NSString *)channel_status_str page:(NSInteger)page;
- (void)getNewsList:(NSInteger)page;
- (void)activateUser:(NSString *)name stutentNum:(NSString *)num password:(NSString *)password;
- (void)login:(NSString *)num password:(NSString *)password;
- (void)logout;
- (void)updateUserDisplayName:(NSString *)display_name 
                        email:(NSString *)email 
                    weiboName:(NSString *)weibo 
                     phoneNum:(NSString *)phone 
                    qqAccount:(NSString *)qq;
- (void)updateUserAvatar:(UIImage *)image;
- (void)updatePassword:(NSString *)new withOldPassword:(NSString *)old;
- (void)likeActivity:(NSString *)activity_id;
- (void)scheduleActivity:(NSString *)activity_id;
- (void)favoriteActivity:(NSString *)activity_id;
- (void)unlikeActivity:(NSString *)activity_id;
- (void)unscheduleActivity:(NSString *)activity_id;
- (void)unfavoriteActivity:(NSString *)activity_id;
- (void)getFavotiteList:(NSInteger)page;
- (void)getCourse;

@end
